### ISSUE TITLE
Support for AndroidX

### ISSUE THREAD

**Issue by davidvavra** [Microsoft/AppCenter-Test-Espresso-Extensions#4]
Espresso now depend on AndroidX and all the documentation is also only about AndroidX libraries, test runner etc. Yet the AppCenter Espresso documentation mentions old test runner from support library.

When I have AndroidX-based tests, the run fails with:

`java.lang.RuntimeException: Delegate runner 'androidx.test.internal.runner.junit4.AndroidJUnit4ClassRunner' for AndroidJUnit4 could not be loaded`

Is AndroidX supported or is the support planned?

**Comment by davidvavra** [comment]
My bad, I had a wrong import. However imho the documentation should be updated with androidx dependencies.

**Comment by john7doe** [comment]
David,

Thanks for the feedback. Version 1.4 has just been released, it should work with your project uses the androidx dependencies.

The changes to the docs is making its way past the reviewers

Br,
/Simon
